import React from "react";
import Link from "next/link";

const Home = () => {
  return (
    <div
      style={{
        height: "100vh",
        padding: "20px",
        backgroundColor: "#232323",
        color: "white",
      }}
    >
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated by{" "}
        <a
          href="https://www.dhiwise.com"
          style={{ color: "#87CEFA", textDecoration: "none" }}
        >
          Dhiwise
        </a>
        .
        <br />
        Quickly use below links to navigate through all pages.
      </p>

      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/landing"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Landing
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/home1"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Home1
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/developerspage"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Developerspage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/abouttheclans"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Abouttheclans
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/games"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Games
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/singlegamespage"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Singlegamespage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/players"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Players
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/playersdetail"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Playersdetail
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/sponsor"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Sponsor
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/events"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Events
          </Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
